version: '3'
services:
    mysql-db:
        image: mysql:latest
        container_name: my-mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - '3306:3306'
        volumes:
          - "./my.cnf:/etc/my.cnf"