version: '3.1'

services:
  postgres-db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - "./db:/var/lib/postgresql"
